#ifndef WEBINTERFACE_H
#define WEBINTERFACE_H

#include "main.h"

// Forward declaration for robot config
extern RobotConfig robotConfig;

// Navigation bar HTML
String navBar(const char* activeTab) {
  String activeStyle = "background: #4CAF50; color: white;";
  String inactiveStyle = "background: #333; color: white;";
  
  return "<nav style='background:#333;padding:15px;margin-bottom:20px;'>"
         "<a href='/' style='color:white;text-decoration:none;padding:10px 20px;margin:5px;border-radius:5px;" + 
         String(strcmp(activeTab, "control") == 0 ? activeStyle : inactiveStyle) + "'>Control</a>"
         "<a href='/kinematics' style='color:white;text-decoration:none;padding:10px 20px;margin:5px;border-radius:5px;" +
         String(strcmp(activeTab, "kinematics") == 0 ? activeStyle : inactiveStyle) + "'>Cinemática Inversa</a>"
         "</nav>";
}

// HTML Page generation function
String htmlPage(const LegAngles& currentLeftLeg, const LegAngles& currentRightLeg) {
  return "<!DOCTYPE html>"
         "<html>"
         "<head>"
         "<meta charset='UTF-8'>"
         "<title>Control Humanoide</title>"
         "<style>"
         "body{font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;background:linear-gradient(135deg,#4f9dfe 0%,#0066cc 100%);min-height:100vh;margin:0;}"
         ".container{max-width:1200px;margin:0 auto;padding:20px;}"
         ".main-box{background:white;border-radius:15px;padding:30px;box-shadow:0 10px 30px rgba(0,0,0,0.3);}"
         ".dpad{display:inline-block;margin:20px;}"
         ".row{display:flex;justify-content:center;}"
         "button{width:80px;height:80px;margin:5px;font-size:20px;border:none;border-radius:10px;background:linear-gradient(135deg,#4f9dfe 0%,#0066cc 100%);color:white;cursor:pointer;transition:transform 0.2s;box-shadow:0 4px 6px rgba(0,0,0,0.2);}"
         "button:hover{transform:scale(1.1);}"
         ".form-section{margin-top:30px;background:#f8f9fa;padding:25px;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,0.1);}"
         ".form-section h3{color:#333;margin-top:0;padding-bottom:15px;border-bottom:3px solid #0066cc;}"
         ".form-section h4{color:#0066cc;margin:20px 0 10px 0;font-size:18px;}"
         ".input-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:15px;margin:20px 0;}"
         ".input-group{display:flex;flex-direction:column;}"
         ".input-group label{font-weight:600;color:#333;margin-bottom:8px;font-size:14px;}"
         ".input-group input{padding:12px;border:2px solid #ddd;border-radius:8px;font-size:16px;transition:border-color 0.2s;}"
         ".input-group input:focus{outline:none;border-color:#0066cc;}"
         "input[type='submit']{background:linear-gradient(135deg,#4f9dfe 0%,#0066cc 100%);color:white;border:none;padding:15px 40px;font-size:18px;border-radius:8px;cursor:pointer;transition:transform 0.2s;margin-top:15px;}"
         "input[type='submit']:hover{transform:scale(1.05);}"
         "h2{color:#333;margin:20px 0;}"
         ".centered{text-align:center;}"
         ".reset-btn{background:linear-gradient(135deg,#ff6b6b 0%,#cc0000 100%);width:auto;padding:15px 30px;font-size:16px;margin:20px auto;display:block;border:none;border-radius:8px;color:white;cursor:pointer;transition:transform 0.2s;box-shadow:0 4px 6px rgba(0,0,0,0.2);}"
         ".reset-btn:hover{transform:scale(1.05);}"
         "</style>"
         "<script>"
         "document.addEventListener('keydown', function(e){"
         "  if(e.key==='w'){ window.location.href='/forward'; }"
         "  else if(e.key==='s'){ window.location.href='/backward'; }"
         "  else if(e.key==='a'){ window.location.href='/left'; }"
         "  else if(e.key==='d'){ window.location.href='/right'; }"
         "});"
         "</script>"
         "</head>"
         "<body>"
         + navBar("control") +
         "<div class='container'>"
         "<div class='main-box'>"
         "<h2 class='centered'>Control de Humanoide</h2>"
         "<div class='centered'>"
         "<div class='dpad'>"
         "<div class='row'><button onclick=\"location.href='/forward'\">&#9650;</button></div>"
         "<div class='row'><button onclick=\"location.href='/left'\">&#9664;</button>"
         "<button onclick=\"location.href='/right'\">&#9654;</button></div>"
         "<div class='row'><button onclick=\"location.href='/backward'\">&#9660;</button></div>"
         "</div>"
         "</div>"
         "<button class='reset-btn' onclick=\"location.href='/reset?from=control'\">Reset a Posición Neutral</button>"
         "<form action='/setservos' method='GET' class='form-section'>"
         "<h3>Posiciones de Servos (0°–180°)</h3>"
         "<div class='input-grid'>"
         "<div class='input-group'><label>Hip L:</label><input type='number' name='hipL' min='0' max='180' value='" + String(currentLeftLeg.hip) + "'></div>"
         "<div class='input-group'><label>Knee L:</label><input type='number' name='kneeL' min='0' max='180' value='" + String(currentLeftLeg.knee) + "'></div>"
         "<div class='input-group'><label>Ankle L:</label><input type='number' name='ankleL' min='0' max='180' value='" + String(currentLeftLeg.ankle) + "'></div>"
         "<div class='input-group'><label>Hip R:</label><input type='number' name='hipR' min='0' max='180' value='" + String(currentRightLeg.hip) + "'></div>"
         "<div class='input-group'><label>Knee R:</label><input type='number' name='kneeR' min='0' max='180' value='" + String(currentRightLeg.knee) + "'></div>"
         "<div class='input-group'><label>Ankle R:</label><input type='number' name='ankleR' min='0' max='180' value='" + String(currentRightLeg.ankle) + "'></div>"
         "</div>"
         "<div class='centered'><input type='submit' value='Actualizar'></div>"
         "</form>"
         "<form action='/setconfig' method='GET' class='form-section'>"
         "<h3>Configuración del Robot</h3>"
         "<h4>Offsets (0°–180°)</h4>"
         "<div class='input-grid'>"
         "<div class='input-group'><label>Hip L Offset:</label><input type='number' name='hipLOffset' min='0' max='180' value='" + String(robotConfig.hipLOffset) + "'></div>"
         "<div class='input-group'><label>Knee L Offset:</label><input type='number' name='kneeLOffset' min='0' max='180' value='" + String(robotConfig.kneeLOffset) + "'></div>"
         "<div class='input-group'><label>Ankle L Offset:</label><input type='number' name='ankleLOffset' min='0' max='180' value='" + String(robotConfig.ankleLOffset) + "'></div>"
         "<div class='input-group'><label>Hip R Offset:</label><input type='number' name='hipROffset' min='0' max='180' value='" + String(robotConfig.hipROffset) + "'></div>"
         "<div class='input-group'><label>Knee R Offset:</label><input type='number' name='kneeROffset' min='0' max='180' value='" + String(robotConfig.kneeROffset) + "'></div>"
         "<div class='input-group'><label>Ankle R Offset:</label><input type='number' name='ankleROffset' min='0' max='180' value='" + String(robotConfig.ankleROffset) + "'></div>"
         "</div>"
         "<h4>Geometría de Piernas (cm)</h4>"
         "<div class='input-grid'>"
         "<div class='input-group'><label>L1 (Upper Leg):</label><input type='number' name='l1' min='0.1' max='20.0' step='0.1' value='" + String(robotConfig.l1) + "'></div>"
         "<div class='input-group'><label>L2 (Lower Leg):</label><input type='number' name='l2' min='0.1' max='20.0' step='0.1' value='" + String(robotConfig.l2) + "'></div>"
         "</div>"
         "<h4>Parámetros de Paso</h4>"
         "<div class='input-grid'>"
         "<div class='input-group'><label>Step Clearance:</label><input type='number' name='stepClearance' min='0.1' max='10.0' step='0.1' value='" + String(robotConfig.stepClearance) + "'></div>"
         "<div class='input-group'><label>Step Height:</label><input type='number' name='stepHeight' min='1.0' max='20.0' step='0.1' value='" + String(robotConfig.stepHeight) + "'></div>"
         "<div class='input-group'><label>Step Length:</label><input type='number' name='stepLength' min='0.5' max='10.0' step='0.1' value='" + String(robotConfig.stepLength) + "'></div>"
         "<div class='input-group'><label>Step Velocity:</label><input type='number' name='stepVelocity' min='1' max='500' step='1' value='" + String(robotConfig.stepVelocity) + "'></div>"
         "<div class='input-group'><label>Step Offset:</label><input type='number' name='stepOffset' min='-5.0' max='5.0' step='0.1' value='" + String(robotConfig.stepOffset) + "'></div>"
         "<div class='input-group'><label>Number of Steps:</label><input type='number' name='numSteps' min='1' max='50' step='1' value='" + String(robotConfig.numSteps) + "'></div>"
         "</div>"
         "<div class='centered'><input type='submit' value='Actualizar'></div>"
         "</form>"
         "</div>"
         "</div>"
         "</body>"
         "</html>";
}

// Interactive Kinematics Page
String htmlKinematicsPage() {
  return "<!DOCTYPE html>"
         "<html>"
         "<head>"
         "<meta charset='UTF-8'>"
         "<title>Cinemática - Humanoide</title>"
         "<style>"
         "body{font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;background:linear-gradient(135deg,#4f9dfe 0%,#0066cc 100%);min-height:100vh;margin:0;}"
         ".container{max-width:1200px;margin:0 auto;padding:20px;}"
         ".main-box{background:white;border-radius:15px;padding:30px;box-shadow:0 10px 30px rgba(0,0,0,0.3);}"
         ".dpad{display:inline-block;margin:20px;}"
         ".row{display:flex;justify-content:center;}"
         "button{width:80px;height:80px;margin:5px;font-size:20px;border:none;border-radius:10px;background:linear-gradient(135deg,#4f9dfe 0%,#0066cc 100%);color:white;cursor:pointer;transition:transform 0.2s;box-shadow:0 4px 6px rgba(0,0,0,0.2);}"
         "button:hover{transform:scale(1.1);}"
         ".reset-btn{background:linear-gradient(135deg,#ff6b6b 0%,#cc0000 100%);width:auto;padding:15px 30px;font-size:16px;margin:20px auto;display:block;border:none;border-radius:8px;color:white;cursor:pointer;transition:transform 0.2s;box-shadow:0 4px 6px rgba(0,0,0,0.2);}"
         ".reset-btn:hover{transform:scale(1.05);}"
         ".centered{text-align:center;}"
         ".data-section{margin-top:30px;background:#f8f9fa;border-radius:10px;padding:25px;}"
         ".data-section h3{color:#333;margin-top:0;border-bottom:2px solid #0066cc;padding-bottom:10px;}"
         ".leg-table{width:100%;margin:20px 0;border-collapse:collapse;background:white;border-radius:8px;overflow:hidden;}"
         ".leg-table th{background:#0066cc;color:white;padding:12px;text-align:left;font-weight:600;}"
         ".leg-table td{padding:10px 12px;border-bottom:1px solid #e0e0e0;}"
         ".leg-table tr:last-child td{border-bottom:none;}"
         ".leg-table tr:nth-child(even){background:#f9f9f9;}"
         ".value-cell{font-weight:bold;color:#333;font-family:'Courier New',monospace;}"
         ".calc-cell{font-size:12px;color:#666;font-style:italic;}"
         ".angle-formula{font-family:'Courier New',monospace;font-size:13px;}"
         ".angle-formula .offset-part{color:#999;font-style:italic;font-weight:normal;}"
         ".process-boxes{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:20px;margin-top:20px;}"
         ".process-box{background:white;padding:20px;border-radius:8px;border-left:5px solid #0066cc;box-shadow:0 2px 8px rgba(0,0,0,0.1);}"
         ".process-box h4{color:#0066cc;margin:0 0 12px 0;font-size:16px;border-bottom:2px solid #e0e0e0;padding-bottom:8px;}"
         ".process-box p{color:#666;margin:8px 0;font-size:14px;line-height:1.6;}"
         ".process-box .formula{background:#f8f9fa;padding:10px;border-radius:5px;font-family:'Courier New',monospace;font-size:12px;color:#333;margin-top:10px;}"
         ".process-box .highlight{color:#4CAF50;font-weight:600;}"
         "</style>"
         "<script>"
         "document.addEventListener('keydown', function(e){"
         "  if(e.key==='w'){ window.location.href='/forward'; }"
         "  else if(e.key==='s'){ window.location.href='/backward'; }"
         "  else if(e.key==='a'){ window.location.href='/left'; }"
         "  else if(e.key==='d'){ window.location.href='/right'; }"
         "});"
         "</script>"
         "</head>"
         "<body>"
         + navBar("kinematics") +
         "<div class='container'>"
         "<div class='main-box'>"
         "<h1 style='color:#333;text-align:center;margin-bottom:30px;'>Visualización de Movimiento</h1>"
         "<div class='centered'>"
         "<div class='dpad'>"
         "<div class='row'><button onclick=\"location.href='/forward'\">&#9650;</button></div>"
         "<div class='row'><button onclick=\"location.href='/left'\">&#9664;</button>"
         "<button onclick=\"location.href='/right'\">&#9654;</button></div>"
         "<div class='row'><button onclick=\"location.href='/backward'\">&#9660;</button></div>"
         "</div>"
         "</div>"
         "<button class='reset-btn' onclick=\"location.href='/reset?from=kinematics'\">Reset a Posición Neutral</button>"
         "<div class='data-section'>"
         "<h3>Estado Actual de los Servos y Cálculos</h3>"
         "<table class='leg-table'>"
         "<thead>"
         "<tr><th>Pierna</th><th>Servo</th><th>Posición Servo</th><th>Offset</th><th>Ángulo Fase 1</th><th>Ángulo Fase 2</th><th>Posición (X, Z)</th></tr>"
         "</thead>"
         "<tbody id='servoData'>"
         "<tr><td rowspan='3' style='vertical-align:middle;font-weight:bold;color:#0066cc;'>Izquierda</td>"
         "<td>Hip</td><td class='value-cell' id='servoL_hip'>-</td><td class='calc-cell' id='offsetL_hip'>-</td><td class='value-cell angle-formula' id='phase1L_hip'>-</td><td class='value-cell angle-formula' id='phase2L_hip'>-</td><td rowspan='3' class='calc-cell' id='posL' style='vertical-align:middle;'>-</td></tr>"
         "<tr><td>Knee</td><td class='value-cell' id='servoL_knee'>-</td><td class='calc-cell' id='offsetL_knee'>-</td><td class='value-cell angle-formula' id='phase1L_knee'>-</td><td class='value-cell angle-formula' id='phase2L_knee'>-</td></tr>"
         "<tr><td>Ankle</td><td class='value-cell' id='servoL_ankle'>-</td><td class='calc-cell' id='offsetL_ankle'>-</td><td class='value-cell angle-formula' id='phase1L_ankle'>-</td><td class='value-cell angle-formula' id='phase2L_ankle'>-</td></tr>"
         "<tr><td rowspan='3' style='vertical-align:middle;font-weight:bold;color:#4CAF50;'>Derecha</td>"
         "<td>Hip</td><td class='value-cell' id='servoR_hip'>-</td><td class='calc-cell' id='offsetR_hip'>-</td><td class='value-cell angle-formula' id='phase1R_hip'>-</td><td class='value-cell angle-formula' id='phase2R_hip'>-</td><td rowspan='3' class='calc-cell' id='posR' style='vertical-align:middle;'>-</td></tr>"
         "<tr><td>Knee</td><td class='value-cell' id='servoR_knee'>-</td><td class='calc-cell' id='offsetR_knee'>-</td><td class='value-cell angle-formula' id='phase1R_knee'>-</td><td class='value-cell angle-formula' id='phase2R_knee'>-</td></tr>"
         "<tr><td>Ankle</td><td class='value-cell' id='servoR_ankle'>-</td><td class='calc-cell' id='offsetR_ankle'>-</td><td class='value-cell angle-formula' id='phase1R_ankle'>-</td><td class='value-cell angle-formula' id='phase2R_ankle'>-</td></tr>"
         "</tbody>"
         "</table>"
         "</div>"
         "<div class='data-section'>"
         "<h3>Proceso de Cálculo de Marcha</h3>"
         "<div class='process-boxes'>"
         "<div class='process-box'>"
         "<h4>1. Cinemática Inversa (IK)</h4>"
         "<p>Dadas las coordenadas <span class='highlight'>(X, Z)</span> del pie, se calculan los ángulos de cadera, rodilla y tobillo necesarios para alcanzar esa posición.</p>"
         "<div class='formula'>hipRad2 = atan(X / Z)<br/>z2 = Z / cos(hipRad2)<br/>hipRad1 = acos((L₁² + z2² - L₂²) / (2·L₁·z2))<br/>kneeRad = π - acos((L₁² + L₂² - z2²) / (2·L₁·L₂))<br/>ankleRad = π/2 + hipRad2 - acos((L₂² + z2² - L₁²) / (2·L₂·z2))</div>"
         "</div>"
         "<div class='process-box'>"
         "<h4>2. Dos Fases de Marcha</h4>"
         "<p><span class='highlight'>Fase 1:</span> Pierna izquierda en apoyo (Z = stepHeight), pierna derecha elevada (Z = stepHeight - stepClearance)</p>"
         "<p><span class='highlight'>Fase 2:</span> Pierna derecha en apoyo (Z = stepHeight), pierna izquierda elevada (Z = stepHeight - stepClearance)</p>"
         "<div class='formula'>Fase 1: L(stepLength, stepHeight), R(-stepLength, stepHeight-stepClearance)<br/>Fase 2: R(stepLength+offset, stepHeight), L(-stepLength, stepHeight-stepClearance)</div>"
         "</div>"
         "<div class='process-box'>"
         "<h4>3. Conversión a Posición de Servo</h4>"
         "<p>Los ángulos calculados se convierten a posiciones de servo aplicando los <span class='highlight'>offsets</span>:</p>"
         "<div class='formula'>Izq: servo = offset - ángulo<br/>Der: servo = offset + ángulo<br/>Tobillo Izq: servo = 2·offset - ángulo</div>"
         "</div>"
         "<div class='process-box'>"
         "<h4>4. Movimiento Progresivo</h4>"
         "<p>El movimiento se realiza interpolando entre las posiciones de las fases, variando X desde <span class='highlight'>stepLength</span> hasta <span class='highlight'>-stepLength</span> en pasos de 0.5 cm.</p>"
         "<div class='formula'>Para cada paso:<br/>- Calcular nueva posición (X, Z)<br/>- Aplicar IK<br/>- Mover servos<br/>- Esperar stepVelocity ms</div>"
         "</div>"
         "</div>"
         "</div>"
         "</div>"
         "</div>"
         "<script>"
         "const PI = 3.14159265359;"
         "let l1 = " + String(robotConfig.l1) + ";"
         "let l2 = " + String(robotConfig.l2) + ";"
         "let hipLOffset = " + String(robotConfig.hipLOffset) + ";"
         "let kneeLOffset = " + String(robotConfig.kneeLOffset) + ";"
         "let ankleLOffset = " + String(robotConfig.ankleLOffset) + ";"
         "let hipROffset = " + String(robotConfig.hipROffset) + ";"
         "let kneeROffset = " + String(robotConfig.kneeROffset) + ";"
         "let ankleROffset = " + String(robotConfig.ankleROffset) + ";"
         "function getCalculatedAngles(hipServo, kneeServo, ankleServo, isLeft) {"
         "  if (isLeft) {"
         "    return {"
         "      hip: hipLOffset - hipServo,"
         "      knee: kneeLOffset - kneeServo,"
         "      ankle: 2 * ankleLOffset - ankleServo"
         "    };"
         "  } else {"
         "    return {"
         "      hip: hipServo - hipROffset,"
         "      knee: kneeServo - kneeROffset,"
         "      ankle: ankleServo - ankleROffset"
         "    };"
         "  }"
         "}"
         "function forwardKinematics(hipDeg, kneeDeg) {"
         "  const hipRad = hipDeg * PI / 180;"
         "  const kneeRad = kneeDeg * PI / 180;"
         "  const z2 = Math.sqrt(l1 * l1 + l2 * l2 - 2 * l1 * l2 * Math.cos(PI - kneeRad));"
         "  if (z2 < 0.1 || isNaN(z2) || !isFinite(z2)) return { x: 0, z: 0, valid: false };"
         "  const cosHipRad1 = (l1 * l1 + z2 * z2 - l2 * l2) / (2 * l1 * z2);"
         "  if (Math.abs(cosHipRad1) > 1) return { x: 0, z: 0, valid: false };"
         "  const hipRad1 = Math.acos(Math.max(-1, Math.min(1, cosHipRad1)));"
         "  const hipRad2 = hipRad - hipRad1;"
         "  if (isNaN(hipRad1) || isNaN(hipRad2)) return { x: 0, z: 0, valid: false };"
         "  const x = z2 * Math.sin(hipRad2);"
         "  const z = z2 * Math.cos(hipRad2);"
         "  return { x: x, z: z, valid: true };"
         "}"
         "let stepHeight = " + String(robotConfig.stepHeight) + ";"
         "let stepLength = " + String(robotConfig.stepLength) + ";"
         "let stepClearance = " + String(robotConfig.stepClearance) + ";"
         "let stepOffset = " + String(robotConfig.stepOffset) + ";"
         "function calculateIK(x, z) {"
         "  function sq(x) { return x * x; }"
         "  if (z <= 0) return null;"
         "  const hipRad2 = Math.atan(x / z);"
         "  const hipDeg2 = hipRad2 * (180 / PI);"
         "  const z2 = z / Math.cos(hipRad2);"
         "  const hipRad1 = Math.acos((sq(l1) + sq(z2) - sq(l2)) / (2 * l1 * z2));"
         "  const hipDeg1 = hipRad1 * (180 / PI);"
         "  const kneeRad = PI - Math.acos((sq(l1) + sq(l2) - sq(z2)) / (2 * l1 * l2));"
         "  const ankleRad = PI / 2 + hipRad2 - Math.acos((sq(l2) + sq(z2) - sq(l1)) / (2 * l2 * z2));"
         "  return {"
         "    hip: hipDeg1 + hipDeg2,"
         "    knee: kneeRad * (180 / PI),"
         "    ankle: ankleRad * (180 / PI)"
         "  };"
         "}"
         "function formatAngleWithOffset(angle, offset, isLeft, isAnkle) {"
         "  let servoPos;"
         "  if (isLeft) {"
         "    if (isAnkle) {"
         "      servoPos = 2 * offset - angle;"
         "      return offset.toFixed(0) + '° <span class=\"offset-part\">× 2 -</span> ' + angle.toFixed(1) + '° <span class=\"offset-part\">=</span> ' + servoPos.toFixed(0) + '°';"
         "    } else {"
         "      servoPos = offset - angle;"
         "      return offset.toFixed(0) + '° <span class=\"offset-part\">-</span> ' + angle.toFixed(1) + '° <span class=\"offset-part\">=</span> ' + servoPos.toFixed(0) + '°';"
         "    }"
         "  } else {"
         "    servoPos = offset + angle;"
         "    return offset.toFixed(0) + '° <span class=\"offset-part\">+</span> ' + angle.toFixed(1) + '° <span class=\"offset-part\">=</span> ' + servoPos.toFixed(0) + '°';"
         "  }"
         "}"
         "function updateServoTable(data) {"
         "  const anglesL = getCalculatedAngles(data.left.hip, data.left.knee, data.left.ankle, true);"
         "  const anglesR = getCalculatedAngles(data.right.hip, data.right.knee, data.right.ankle, false);"
         "  const posL = forwardKinematics(anglesL.hip, anglesL.knee);"
         "  const posR = forwardKinematics(anglesR.hip, anglesR.knee);"
         "  document.getElementById('servoL_hip').textContent = data.left.hip + '°';"
         "  document.getElementById('servoL_knee').textContent = data.left.knee + '°';"
         "  document.getElementById('servoL_ankle').textContent = data.left.ankle + '°';"
         "  document.getElementById('servoR_hip').textContent = data.right.hip + '°';"
         "  document.getElementById('servoR_knee').textContent = data.right.knee + '°';"
         "  document.getElementById('servoR_ankle').textContent = data.right.ankle + '°';"
         "  document.getElementById('offsetL_hip').textContent = 'Offset: ' + hipLOffset + '°';"
         "  document.getElementById('offsetL_knee').textContent = 'Offset: ' + kneeLOffset + '°';"
         "  document.getElementById('offsetL_ankle').textContent = 'Offset: ' + ankleLOffset + '°';"
         "  document.getElementById('offsetR_hip').textContent = 'Offset: ' + hipROffset + '°';"
         "  document.getElementById('offsetR_knee').textContent = 'Offset: ' + kneeROffset + '°';"
         "  document.getElementById('offsetR_ankle').textContent = 'Offset: ' + ankleROffset + '°';"
         "  const phase1L = calculateIK(stepLength, stepHeight);"
         "  const phase1R = calculateIK(-stepLength, stepHeight - stepClearance);"
         "  const phase2R = calculateIK(stepLength + stepOffset, stepHeight);"
         "  const phase2L = calculateIK(-stepLength, stepHeight - stepClearance);"
         "  if (phase1L) {"
         "    document.getElementById('phase1L_hip').innerHTML = formatAngleWithOffset(phase1L.hip, hipLOffset, true, false);"
         "    document.getElementById('phase1L_knee').innerHTML = formatAngleWithOffset(phase1L.knee, kneeLOffset, true, false);"
         "    document.getElementById('phase1L_ankle').innerHTML = formatAngleWithOffset(phase1L.ankle, ankleLOffset, true, true);"
         "  }"
         "  if (phase1R) {"
         "    document.getElementById('phase1R_hip').innerHTML = formatAngleWithOffset(phase1R.hip, hipROffset, false, false);"
         "    document.getElementById('phase1R_knee').innerHTML = formatAngleWithOffset(phase1R.knee, kneeROffset, false, false);"
         "    document.getElementById('phase1R_ankle').innerHTML = formatAngleWithOffset(phase1R.ankle, ankleROffset, false, false);"
         "  }"
         "  if (phase2R) {"
         "    document.getElementById('phase2R_hip').innerHTML = formatAngleWithOffset(phase2R.hip, hipROffset, false, false);"
         "    document.getElementById('phase2R_knee').innerHTML = formatAngleWithOffset(phase2R.knee, kneeROffset, false, false);"
         "    document.getElementById('phase2R_ankle').innerHTML = formatAngleWithOffset(phase2R.ankle, ankleROffset, false, false);"
         "  }"
         "  if (phase2L) {"
         "    document.getElementById('phase2L_hip').innerHTML = formatAngleWithOffset(phase2L.hip, hipLOffset, true, false);"
         "    document.getElementById('phase2L_knee').innerHTML = formatAngleWithOffset(phase2L.knee, kneeLOffset, true, false);"
         "    document.getElementById('phase2L_ankle').innerHTML = formatAngleWithOffset(phase2L.ankle, ankleLOffset, true, true);"
         "  }"
         "  if (posL.valid) {"
         "    document.getElementById('posL').textContent = 'X: ' + posL.x.toFixed(2) + 'cm, Z: ' + posL.z.toFixed(2) + 'cm';"
         "  } else {"
         "    document.getElementById('posL').textContent = 'Inválido';"
         "  }"
         "  if (posR.valid) {"
         "    document.getElementById('posR').textContent = 'X: ' + posR.x.toFixed(2) + 'cm, Z: ' + posR.z.toFixed(2) + 'cm';"
         "  } else {"
         "    document.getElementById('posR').textContent = 'Inválido';"
         "  }"
         "}"
         "function updateLegs() {"
         "  fetch('/getlegs')"
         "    .then(response => response.json())"
         "    .then(data => {"
         "      updateServoTable(data);"
         "    })"
         "    .catch(error => console.error('Error:', error));"
         "}"
         "setInterval(updateLegs, 200);"
         "updateLegs();"
         "</script>"
         "</body>"
         "</html>";
}

#endif // WEBINTERFACE_H
