#ifndef WEBINTERFACE_H
#define WEBINTERFACE_H

#include "main.h"

// Forward declaration for robot config
extern RobotConfig robotConfig;

// Navigation bar HTML
String navBar(const char* activeTab) {
  String activeStyle = "background: #4CAF50; color: white;";
  String inactiveStyle = "background: #333; color: white;";
  
  return "<nav style='background:#333;padding:15px;margin-bottom:20px;'>"
         "<a href='/' style='color:white;text-decoration:none;padding:10px 20px;margin:5px;border-radius:5px;" + 
         String(strcmp(activeTab, "control") == 0 ? activeStyle : inactiveStyle) + "'>Control</a>"
         "<a href='/kinematics' style='color:white;text-decoration:none;padding:10px 20px;margin:5px;border-radius:5px;" +
         String(strcmp(activeTab, "kinematics") == 0 ? activeStyle : inactiveStyle) + "'>Cinemática Inversa</a>"
         "</nav>";
}

// HTML Page generation function
String htmlPage(const LegAngles& currentLeftLeg, const LegAngles& currentRightLeg) {
  return "<!DOCTYPE html>"
         "<html>"
         "<head>"
         "<meta charset='UTF-8'>"
         "<title>Control Humanoide</title>"
         "<style>"
         "body{font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;background:linear-gradient(135deg,#4f9dfe 0%,#0066cc 100%);min-height:100vh;margin:0;}"
         ".container{max-width:1200px;margin:0 auto;padding:20px;}"
         ".main-box{background:white;border-radius:15px;padding:30px;box-shadow:0 10px 30px rgba(0,0,0,0.3);}"
         ".dpad{display:inline-block;margin:20px;}"
         ".row{display:flex;justify-content:center;}"
         "button{width:80px;height:80px;margin:5px;font-size:20px;border:none;border-radius:10px;background:linear-gradient(135deg,#4f9dfe 0%,#0066cc 100%);color:white;cursor:pointer;transition:transform 0.2s;box-shadow:0 4px 6px rgba(0,0,0,0.2);}"
         "button:hover{transform:scale(1.1);}"
         ".form-section{margin-top:30px;background:#f8f9fa;padding:25px;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,0.1);}"
         ".form-section h3{color:#333;margin-top:0;padding-bottom:15px;border-bottom:3px solid #0066cc;}"
         ".form-section h4{color:#0066cc;margin:20px 0 10px 0;font-size:18px;}"
         ".input-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:15px;margin:20px 0;}"
         ".input-group{display:flex;flex-direction:column;}"
         ".input-group label{font-weight:600;color:#333;margin-bottom:8px;font-size:14px;}"
         ".input-group input{padding:12px;border:2px solid #ddd;border-radius:8px;font-size:16px;transition:border-color 0.2s;}"
         ".input-group input:focus{outline:none;border-color:#0066cc;}"
         "input[type='submit']{background:linear-gradient(135deg,#4f9dfe 0%,#0066cc 100%);color:white;border:none;padding:15px 40px;font-size:18px;border-radius:8px;cursor:pointer;transition:transform 0.2s;margin-top:15px;}"
         "input[type='submit']:hover{transform:scale(1.05);}"
         "h2{color:#333;margin:20px 0;}"
         ".centered{text-align:center;}"
         "</style>"
         "<script>"
         "document.addEventListener('keydown', function(e){"
         "  if(e.key==='w'){ window.location.href='/forward'; }"
         "  else if(e.key==='s'){ window.location.href='/backward'; }"
         "  else if(e.key==='a'){ window.location.href='/left'; }"
         "  else if(e.key==='d'){ window.location.href='/right'; }"
         "});"
         "</script>"
         "</head>"
         "<body>"
         + navBar("control") +
         "<div class='container'>"
         "<div class='main-box'>"
         "<h2 class='centered'>Control de Humanoide</h2>"
         "<div class='centered'>"
         "<div class='dpad'>"
         "<div class='row'><button onclick=\"location.href='/forward'\">&#9650;</button></div>"
         "<div class='row'><button onclick=\"location.href='/left'\">&#9664;</button>"
         "<button onclick=\"location.href='/right'\">&#9654;</button></div>"
         "<div class='row'><button onclick=\"location.href='/backward'\">&#9660;</button></div>"
         "</div>"
         "</div>"
         "<form action='/setservos' method='GET' class='form-section'>"
         "<h3>Posiciones de Servos (0°–180°)</h3>"
         "<div class='input-grid'>"
         "<div class='input-group'><label>Hip L:</label><input type='number' name='hipL' min='0' max='180' value='" + String(currentLeftLeg.hip) + "'></div>"
         "<div class='input-group'><label>Knee L:</label><input type='number' name='kneeL' min='0' max='180' value='" + String(currentLeftLeg.knee) + "'></div>"
         "<div class='input-group'><label>Ankle L:</label><input type='number' name='ankleL' min='0' max='180' value='" + String(currentLeftLeg.ankle) + "'></div>"
         "<div class='input-group'><label>Hip R:</label><input type='number' name='hipR' min='0' max='180' value='" + String(currentRightLeg.hip) + "'></div>"
         "<div class='input-group'><label>Knee R:</label><input type='number' name='kneeR' min='0' max='180' value='" + String(currentRightLeg.knee) + "'></div>"
         "<div class='input-group'><label>Ankle R:</label><input type='number' name='ankleR' min='0' max='180' value='" + String(currentRightLeg.ankle) + "'></div>"
         "</div>"
         "<div class='centered'><input type='submit' value='Actualizar'></div>"
         "</form>"
         "<form action='/setconfig' method='GET' class='form-section'>"
         "<h3>Configuración del Robot</h3>"
         "<h4>Offsets (0°–180°)</h4>"
         "<div class='input-grid'>"
         "<div class='input-group'><label>Hip L Offset:</label><input type='number' name='hipLOffset' min='0' max='180' value='" + String(robotConfig.hipLOffset) + "'></div>"
         "<div class='input-group'><label>Knee L Offset:</label><input type='number' name='kneeLOffset' min='0' max='180' value='" + String(robotConfig.kneeLOffset) + "'></div>"
         "<div class='input-group'><label>Ankle L Offset:</label><input type='number' name='ankleLOffset' min='0' max='180' value='" + String(robotConfig.ankleLOffset) + "'></div>"
         "<div class='input-group'><label>Hip R Offset:</label><input type='number' name='hipROffset' min='0' max='180' value='" + String(robotConfig.hipROffset) + "'></div>"
         "<div class='input-group'><label>Knee R Offset:</label><input type='number' name='kneeROffset' min='0' max='180' value='" + String(robotConfig.kneeROffset) + "'></div>"
         "<div class='input-group'><label>Ankle R Offset:</label><input type='number' name='ankleROffset' min='0' max='180' value='" + String(robotConfig.ankleROffset) + "'></div>"
         "</div>"
         "<h4>Geometría de Piernas (cm)</h4>"
         "<div class='input-grid'>"
         "<div class='input-group'><label>L1 (Upper Leg):</label><input type='number' name='l1' min='0.1' max='20.0' step='0.1' value='" + String(robotConfig.l1) + "'></div>"
         "<div class='input-group'><label>L2 (Lower Leg):</label><input type='number' name='l2' min='0.1' max='20.0' step='0.1' value='" + String(robotConfig.l2) + "'></div>"
         "</div>"
         "<h4>Parámetros de Paso</h4>"
         "<div class='input-grid'>"
         "<div class='input-group'><label>Step Clearance:</label><input type='number' name='stepClearance' min='0.1' max='10.0' step='0.1' value='" + String(robotConfig.stepClearance) + "'></div>"
         "<div class='input-group'><label>Step Height:</label><input type='number' name='stepHeight' min='1.0' max='20.0' step='0.1' value='" + String(robotConfig.stepHeight) + "'></div>"
         "<div class='input-group'><label>Step Length:</label><input type='number' name='stepLength' min='0.5' max='10.0' step='0.1' value='" + String(robotConfig.stepLength) + "'></div>"
         "<div class='input-group'><label>Step Velocity:</label><input type='number' name='stepVelocity' min='1' max='500' step='1' value='" + String(robotConfig.stepVelocity) + "'></div>"
         "<div class='input-group'><label>Step Offset:</label><input type='number' name='stepOffset' min='-5.0' max='5.0' step='0.1' value='" + String(robotConfig.stepOffset) + "'></div>"
         "<div class='input-group'><label>Number of Steps:</label><input type='number' name='numSteps' min='1' max='50' step='1' value='" + String(robotConfig.numSteps) + "'></div>"
         "</div>"
         "<div class='centered'><input type='submit' value='Actualizar'></div>"
         "</form>"
         "</div>"
         "</div>"
         "</body>"
         "</html>";
}

// Interactive Kinematics Page
String htmlKinematicsPage() {
  return "<!DOCTYPE html>"
         "<html>"
         "<head>"
         "<meta charset='UTF-8'>"
         "<title>Cinemática Inversa - Humanoide</title>"
         "<style>"
         "body{font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;background:linear-gradient(135deg,#4f9dfe 0%,#0066cc 100%);min-height:100vh;margin:0;}"
         ".container{max-width:1200px;margin:0 auto;padding:20px;}"
         ".main-box{background:white;border-radius:15px;padding:30px;box-shadow:0 10px 30px rgba(0,0,0,0.3);}"
         ".input-section{display:flex;gap:30px;margin-bottom:30px;flex-wrap:wrap;}"
         ".input-group{flex:1;min-width:200px;}"
         ".input-group label{display:block;margin-bottom:8px;color:#333;font-weight:600;}"
         ".input-group input{padding:12px;border:2px solid #ddd;border-radius:8px;font-size:16px;width:100%;box-sizing:border-box;}"
         ".input-group input:focus{outline:none;border-color:#0066cc;}"
         ".calculate-btn{background:linear-gradient(135deg,#4f9dfe 0%,#0066cc 100%);color:white;border:none;padding:15px 40px;font-size:18px;border-radius:8px;cursor:pointer;transition:transform 0.2s;width:100%;margin-top:15px;}"
         ".calculate-btn:hover{transform:scale(1.05);}"
         ".results-section{margin-top:30px;display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:20px;}"
         ".result-card{background:#f8f9fa;border-left:4px solid #0066cc;padding:20px;border-radius:8px;}"
         ".result-card h4{margin-top:0;color:#0066cc;}"
         ".result-value{font-size:24px;font-weight:bold;color:#333;margin:10px 0;}"
         ".calculation-steps{margin-top:30px;background:#f8f9fa;border-radius:10px;padding:25px;}"
         ".calculation-steps h3{color:#333;border-bottom:2px solid #0066cc;padding-bottom:10px;}"
         ".step{background:white;margin:15px 0;padding:15px;border-radius:8px;border-left:3px solid #4CAF50;}"
         ".step-title{font-weight:600;color:#4CAF50;margin-bottom:8px;}"
         ".step-equation{font-family:'Courier New',monospace;background:#e9ecef;padding:8px;border-radius:5px;margin:5px 0;overflow-x:auto;}"
         ".canvas-container{text-align:center;margin:30px 0;background:#f8f9fa;border-radius:10px;padding:20px;}"
         ".canvas-container h3{color:#333;margin-bottom:15px;}"
         "canvas{border:2px solid #ddd;border-radius:8px;background:white;max-width:100%;}"
         "</style>"
         "</head>"
         "<body>"
         + navBar("kinematics") +
         "<div class='container'>"
         "<div class='main-box'>"
         "<h1 style='color:#333;text-align:center;margin-bottom:30px;'>Cinemática Inversa</h1>"
         "<div class='input-section'>"
         "<div class='input-group'>"
         "<label>Posición X (cm):</label>"
         "<input type='number' id='posX' value='0' step='0.1' min='-10' max='10'>"
         "</div>"
         "<div class='input-group'>"
         "<label>Posición Z (cm):</label>"
         "<input type='number' id='posZ' value='10' step='0.1' min='5' max='15'>"
         "</div>"
         "<div class='input-group'>"
         "<label>Longitud L1 (cm):</label>"
         "<input type='number' id='lengthL1' value='" + String(robotConfig.l1) + "' step='0.1' min='1' max='20' readonly style='background:#e9ecef;'>"
         "</div>"
         "<div class='input-group'>"
         "<label>Longitud L2 (cm):</label>"
         "<input type='number' id='lengthL2' value='" + String(robotConfig.l2) + "' step='0.1' min='1' max='20' readonly style='background:#e9ecef;'>"
         "</div>"
         "</div>"
         "<button class='calculate-btn' onclick='calculate()'>Calcular Ángulos</button>"
         "<div class='results-section' id='results' style='display:none;'>"
         "<div class='result-card'>"
         "<h4>Ángulo de Cadera</h4>"
         "<div class='result-value' id='hipAngle'>0°</div>"
         "</div>"
         "<div class='result-card'>"
         "<h4>Ángulo de Rodilla</h4>"
         "<div class='result-value' id='kneeAngle'>0°</div>"
         "</div>"
         "<div class='result-card'>"
         "<h4>Ángulo de Tobillo</h4>"
         "<div class='result-value' id='ankleAngle'>0°</div>"
         "</div>"
         "</div>"
         "<div class='canvas-container'>"
         "<h3>Visualización de la Pierna</h3>"
         "<canvas id='legCanvas' width='300' height='400'></canvas>"
         "</div>"
         "<div class='calculation-steps' id='steps' style='display:none;'>"
         "<h3>Pasos de Cálculo</h3>"
         "<div class='step'>"
         "<div class='step-title'>Paso 1: Calcular Ángulo de Cadera Horizontal</div>"
         "<div class='step-equation'>hipRad2 = atan(x / z)</div>"
         "<div class='step-equation' id='step1-result'></div>"
         "</div>"
         "<div class='step'>"
         "<div class='step-title'>Paso 2: Ajustar Z usando el ángulo horizontal</div>"
         "<div class='step-equation'>z2 = z / cos(hipRad2)</div>"
         "<div class='step-equation' id='step2-result'></div>"
         "</div>"
         "<div class='step'>"
         "<div class='step-title'>Paso 3: Calcular Ángulo del Triángulo Principal</div>"
         "<div class='step-equation'>hipRad1 = acos((L₁² + z2² - L₂²) / (2 × L₁ × z2))</div>"
         "<div class='step-equation' id='step3-result'></div>"
         "</div>"
         "<div class='step'>"
         "<div class='step-title'>Paso 4: Calcular Ángulo de Rodilla</div>"
         "<div class='step-equation'>kneeRad = π - acos((L₁² + L₂² - z2²) / (2 × L₁ × L₂))</div>"
         "<div class='step-equation' id='step4-result'></div>"
         "</div>"
         "<div class='step'>"
         "<div class='step-title'>Paso 5: Calcular Ángulo de Tobillo</div>"
         "<div class='step-equation'>ankleRad = π/2 + hipRad2 - acos((L₂² + z2² - L₁²) / (2 × L₂ × z2))</div>"
         "<div class='step-equation' id='step5-result'></div>"
         "</div>"
         "<div class='step'>"
         "<div class='step-title'>Paso 6: Ángulo Final de Cadera</div>"
         "<div class='step-equation'>hipDeg = hipDeg1 + hipDeg2</div>"
         "<div class='step-equation' id='step6-result'></div>"
         "</div>"
         "</div>"
         "</div>"
         "</div>"
         "<script>"
         "const PI = 3.14159265359;"
         "function sq(x) { return x * x; }"
         "function calculate() {"
         "  const x = parseFloat(document.getElementById('posX').value);"
         "  const z = parseFloat(document.getElementById('posZ').value);"
         "  const l1 = parseFloat(document.getElementById('lengthL1').value);"
         "  const l2 = parseFloat(document.getElementById('lengthL2').value);"
         "  if (isNaN(x) || isNaN(z) || z <= 0) {"
         "    alert('Por favor ingrese valores válidos. Z debe ser positivo.');"
         "    return;"
         "  }"
         "  const hipRad2 = Math.atan(x / z);"
         "  const hipDeg2 = hipRad2 * (180 / PI);"
         "  const z2 = z / Math.cos(hipRad2);"
         "  const hipRad1 = Math.acos((sq(l1) + sq(z2) - sq(l2)) / (2 * l1 * z2));"
         "  const hipDeg1 = hipRad1 * (180 / PI);"
         "  const kneeRad = PI - Math.acos((sq(l1) + sq(l2) - sq(z2)) / (2 * l1 * l2));"
         "  const ankleRad = PI / 2 + hipRad2 - Math.acos((sq(l2) + sq(z2) - sq(l1)) / (2 * l2 * z2));"
         "  const hipDeg = hipDeg1 + hipDeg2;"
         "  const kneeDeg = kneeRad * (180 / PI);"
         "  const ankleDeg = ankleRad * (180 / PI);"
         "  document.getElementById('hipAngle').textContent = hipDeg.toFixed(2) + '°';"
         "  document.getElementById('kneeAngle').textContent = kneeDeg.toFixed(2) + '°';"
         "  document.getElementById('ankleAngle').textContent = ankleDeg.toFixed(2) + '°';"
         "  document.getElementById('step1-result').textContent = 'hipRad2 = atan(' + x.toFixed(2) + ' / ' + z.toFixed(2) + ') = ' + hipRad2.toFixed(4) + ' rad (' + hipDeg2.toFixed(2) + '°)';"
         "  document.getElementById('step2-result').textContent = 'z2 = ' + z.toFixed(2) + ' / cos(' + hipRad2.toFixed(4) + ') = ' + z2.toFixed(4) + ' cm';"
         "  document.getElementById('step3-result').textContent = 'hipRad1 = acos((' + sq(l1).toFixed(2) + ' + ' + sq(z2).toFixed(2) + ' - ' + sq(l2).toFixed(2) + ') / (2 × ' + l1.toFixed(2) + ' × ' + z2.toFixed(2) + ')) = ' + hipRad1.toFixed(4) + ' rad (' + hipDeg1.toFixed(2) + '°)';"
         "  document.getElementById('step4-result').textContent = 'kneeRad = π - acos((' + sq(l1).toFixed(2) + ' + ' + sq(l2).toFixed(2) + ' - ' + sq(z2).toFixed(2) + ') / (2 × ' + l1.toFixed(2) + ' × ' + l2.toFixed(2) + ')) = ' + kneeRad.toFixed(4) + ' rad (' + kneeDeg.toFixed(2) + '°)';"
         "  document.getElementById('step5-result').textContent = 'ankleRad = π/2 + ' + hipRad2.toFixed(4) + ' - acos((' + sq(l2).toFixed(2) + ' + ' + sq(z2).toFixed(2) + ' - ' + sq(l1).toFixed(2) + ') / (2 × ' + l2.toFixed(2) + ' × ' + z2.toFixed(2) + ')) = ' + ankleRad.toFixed(4) + ' rad (' + ankleDeg.toFixed(2) + '°)';"
         "  document.getElementById('step6-result').textContent = 'hipDeg = ' + hipDeg1.toFixed(2) + '° + ' + hipDeg2.toFixed(2) + '° = ' + hipDeg.toFixed(2) + '°';"
         "  document.getElementById('results').style.display = 'grid';"
         "  document.getElementById('steps').style.display = 'block';"
         "  drawLeg(x, z, l1, l2, hipDeg, kneeDeg, ankleDeg);"
         "}"
         "function drawLeg(x, z, l1, l2, hipDeg, kneeDeg, ankleDeg) {"
         "  const canvas = document.getElementById('legCanvas');"
         "  const ctx = canvas.getContext('2d');"
         "  ctx.clearRect(0, 0, canvas.width, canvas.height);"
         "  const centerX = canvas.width / 2;"
         "  const topY = 50;"
         "  const scale = 15;"
         "  const hipRad2 = Math.atan(x / z);"
         "  const z2 = z / Math.cos(hipRad2);"
         "  const hipRad1 = Math.acos((sq(l1) + sq(z2) - sq(l2)) / (2 * l1 * z2));"
         "  const hipAngle = hipRad1 + hipRad2;"
         "  const kneeAngle = PI - Math.acos((sq(l1) + sq(l2) - sq(z2)) / (2 * l1 * l2));"
         "  ctx.strokeStyle = '#0066cc';"
         "  ctx.lineWidth = 8;"
         "  ctx.lineCap = 'round';"
         "  const endX1 = centerX + Math.cos(PI/2 - hipAngle) * l1 * scale;"
         "  const endY1 = topY + Math.sin(PI/2 - hipAngle) * l1 * scale;"
         "  const endX2 = endX1 + Math.cos(PI/2 - hipAngle - kneeAngle) * l2 * scale;"
         "  const endY2 = endY1 + Math.sin(PI/2 - hipAngle - kneeAngle) * l2 * scale;"
         "  ctx.beginPath();"
         "  ctx.moveTo(centerX, topY);"
         "  ctx.lineTo(endX1, endY1);"
         "  ctx.lineTo(endX2, endY2);"
         "  ctx.stroke();"
         "  ctx.fillStyle = '#0066cc';"
         "  ctx.beginPath();"
         "  ctx.arc(centerX, topY, 8, 0, 2 * PI);"
         "  ctx.fill();"
         "  ctx.fillStyle = '#4CAF50';"
         "  ctx.beginPath();"
         "  ctx.arc(endX1, endY1, 8, 0, 2 * PI);"
         "  ctx.fill();"
         "  ctx.fillStyle = '#ff6b6b';"
         "  ctx.beginPath();"
         "  ctx.arc(endX2, endY2, 8, 0, 2 * PI);"
         "  ctx.fill();"
         "  ctx.fillStyle = '#333';"
         "  ctx.font = '12px Arial';"
         "  ctx.fillText('Cadera', centerX + 15, topY);"
         "  ctx.fillText('Rodilla', endX1 + 15, endY1);"
         "  ctx.fillText('Tobillo', endX2 + 15, endY2);"
         "}"
         "calculate();"
         "</script>"
         "</body>"
         "</html>";
}

#endif // WEBINTERFACE_H
